# site settings
title: Grimheden Holdings
subtitle: World leading asset management
email: inquiries@grimhedenholdings.com
description: "Assertive investing: Resilience amid uncertainty"
baseurl: https://grimhedenholdings.com # the subpath of your site, e.g. /blog
url: https://grimhedenholdings.com # the base hostname & protocol for your site
author: Simon Grimheden
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
